##### Numpy

Numpy is a fundamental library for scientific computing in python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

In [2]:
import numpy as np

In [13]:
##Creating a 1D array:

arr1=np.array([1,2,3,4,5,6])
print(type(arr1))
print(arr1.shape)
print(arr1)

<class 'numpy.ndarray'>
(6,)
[1 2 3 4 5 6]


In [15]:
##Reshaping the array to 2D array using reshape:
arr2=np.array([1,2,3,4,5,6])
arr3=arr2.reshape(3,2) ##reshape doesn't modify original array, returns a new array
arr3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
##Reshaping the array to 2D array using shape:
arr4=np.array([1,2,3,4,5,6])
arr4.shape=(2,3)  ##shape modifies the original array
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr5=np.array([[1,2],[3,4],[5,6]]) 
print(arr5.shape) ##3 rows, 2 columns
print(arr5)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [22]:
np.arange(1,10,2).reshape(5,1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [23]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
##identity matrix:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
##Attributes of numpy array
arr=np.array([[1,2,3],[4,5,6]])
print("Array: ", arr)
print("Shape: ", arr.shape)
print("Number of dimensions: ", arr.ndim)
print("Size or number of elements: ", arr.size)
print("Data type: ", arr.dtype)
print("Item size in bytes: ", arr.itemsize)

Array:  [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of dimensions:  2
Size or number of elements:  6
Data type:  int64
Item size in bytes:  8


In [28]:
##Numpy vectorised operations:

arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

##Element-wise addition:
print("Addition: ",arr1+arr2)

##Element-wise substraction:
print("Substraction: ", arr1-arr2)

##Element wise Multiplication:
print("Multiplication: ", arr1*arr2)

##Element wise Division:
print("Division: ", arr1/arr2)

Addition:  [11 22 33 44 55]
Substraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [30]:
##Universal functions- applies to entire array:

arr=np.array([2,3,4,5,6])

##Sqaure root
print(np.sqrt(arr))

##Exponential:
print(np.exp(arr))

##Sine:
print(np.sin(arr))

##natural log:
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [31]:
##Array slicing and indexing:

arr=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [32]:
arr[0]

array([1, 2, 3, 4])

In [34]:
print(arr[0][0])

1


In [35]:
print(arr[1:])

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [36]:
print(arr[1:,2:])

[[ 7  8]
 [11 12]]


In [37]:
print(arr[0:2])

[[1 2 3 4]
 [5 6 7 8]]


In [39]:
print(arr[0:2, 2:])

[[3 4]
 [7 8]]


In [40]:
print(arr[1:, 1:3])

[[ 6  7]
 [10 11]]


In [41]:
##Modify array elements:

arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [42]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [45]:
## Statistical Concept- Normalization
## Mean is zero and Standard deviation is one

data=np.array([1,2,3,4,5])

##Calculating the mean and standard deviation:
mean=np.mean(data)
std_dev=np.std(data)

##Normalize the data: (Standard normal distribution)
normalized_data=(data-mean)/std_dev
print("Normalized data: ", normalized_data)

Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [46]:
##Statistical calculations:
data=np.array([1,2,3,4,5,6,7,8,9,10])

##Mean:
mean=np.mean(data)
print("Mean: ", mean)

##Median:
median=np.median(data)
print("Median: ", median)

##Standard Deviation:
std_dev=np.std(data)
print("Standard Deviation: ", std_dev)

##Variance:
var=np.var(data)
print("Variance: ",var)

Mean:  5.5
Median:  5.5
Standard Deviation:  2.8722813232690143
Variance:  8.25


In [47]:
##Logical Operations:
data=np.array([1,2,3,4,5,6,7,8,9,10])

data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [48]:
data[data>5]

array([ 6,  7,  8,  9, 10])

In [ ]:
data[(data>=5) & (data<=8)] ##and will not work here. Only logical & and will work

array([5, 6, 7, 8])